spring:
  h2:
    console:
        enabled: true
        path: '/console'
  datasource:
    url:
      jdbc:h2:file:C:\Users\Jaroslaw\Desktop\todo-app\todo-db;DB_CLOSE_DELAY=-1
  jpa.hibernate:
    ddl-auto: validate
  flyway:
    baselineOnMigrate: true